package com.dongguk.untactstudy

class StudyModel(
    val studyRoomNumber: Long,
    val studyName: String,
    val studyInfo: String,
    val studyMemberAmount: String,
    val year: String,
    val month: String,
    val day: String,
    val sort1st: String,
    val sort2nd: String,
    var studyIndex1: String,
    var studyIndex2: String,
    var studyIndex3: String,
    var studyIndex4: String,
    var studyIndex5: String,
    var studyIndex6: String,
    var studyIndex7: String,
    var studyIndex8: String,
    var studyIndex9: String,
    var studyIndex10: String,
    var studyIndex11: String,
    var studyIndex12: String,
    var studyIndex13: String,
    var studyIndex14: String,
    var studyIndex15: String,
    var studyIndex16: String,
    val userid: String
)